### ISSUE TITLE
Fulfil the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/jem.js#3]
## General Items
- [x] It has a github repo
- [x] It has a proper Apache2 LICENSE file.
- [x] It's has a clear and useful README.md
- [x] It's documented (with examples)
- [x] It's tested.
- [x] It's hooked to the [open-source hipchat room](http://inaka.net/hipchat)
- [x] It has a link to the [open-source hipchat room](http://inaka.net/hipchat) in its README.
- [x] It has a link to [inaka.github.io](http://inaka.github.io) in its README and/or landing page.
## Exhibition
- [x] There is a blog post about it.
- [ ] It's shared on social networks.
- [ ] It's shared on reddit.
- [x] It's shared on hacker news with a title like Show HN: description.
- [x] It has a landing page built in github pages.
## For Libraries
- [x] It provides a sample application.
- [x] Examples of use are documented in the README or linked from there.
## For JS Projects
- [x] It's checked with [Hound](https://houndci.com)
- [x] It's published as an npm package.
